# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\GoldenGoose\UI\분별가격정보백업.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(586, 231)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_4 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.comboBox = QtWidgets.QComboBox(self.splitter_4)
        self.comboBox.setObjectName("comboBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(131, 23))
        self.pushButton_3.setMaximumSize(QtCore.QSize(131, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.splitter_4, 1, 0, 1, 1)
        self.splitter_5 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.progressBar = QtWidgets.QProgressBar(self.splitter_5)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_4 = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_4.setMinimumSize(QtCore.QSize(131, 23))
        self.pushButton_4.setMaximumSize(QtCore.QSize(131, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.splitter_5, 2, 0, 1, 1)
        self.comboBox_min = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_min.setMinimumSize(QtCore.QSize(71, 20))
        self.comboBox_min.setMaximumSize(QtCore.QSize(71, 20))
        self.comboBox_min.setObjectName("comboBox_min")
        self.comboBox_min.addItem("")
        self.comboBox_min.addItem("")
        self.comboBox_min.addItem("")
        self.comboBox_min.addItem("")
        self.comboBox_min.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_min, 0, 0, 1, 1)
        self.label_codename = QtWidgets.QLabel(self.groupBox_2)
        self.label_codename.setText("")
        self.label_codename.setObjectName("label_codename")
        self.gridLayout_2.addWidget(self.label_codename, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 48))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 48))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter.setMinimumSize(QtCore.QSize(150, 16))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.radioButton_all = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_all.setObjectName("radioButton_all")
        self.radioButton_inc = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_inc.setChecked(True)
        self.radioButton_inc.setObjectName("radioButton_inc")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.pushButton_3.clicked.connect(Dialog.Backup_One) # type: ignore
        self.pushButton_4.clicked.connect(Dialog.Backup_All) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "분별가격정보 백업"))
        self.groupBox_2.setTitle(_translate("Dialog", "분봉"))
        self.pushButton_3.setText(_translate("Dialog", "한 종목 백업(분봉)"))
        self.pushButton_4.setText(_translate("Dialog", "전 종목 백업(분봉)"))
        self.comboBox_min.setItemText(0, _translate("Dialog", "0 : 30초"))
        self.comboBox_min.setItemText(1, _translate("Dialog", "1 : 1분"))
        self.comboBox_min.setItemText(2, _translate("Dialog", "2 : 3분"))
        self.comboBox_min.setItemText(3, _translate("Dialog", "3 : 5분"))
        self.comboBox_min.setItemText(4, _translate("Dialog", "4 : 10분"))
        self.groupBox_3.setTitle(_translate("Dialog", "백업방법"))
        self.radioButton_all.setText(_translate("Dialog", "전체 백업"))
        self.radioButton_inc.setText(_translate("Dialog", "추가 백업"))
