# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\GoldenGoose\UI\종목별투자자정보백업.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(586, 220)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 48))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 48))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter.setMinimumSize(QtCore.QSize(150, 16))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.radioButton_all = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_all.setObjectName("radioButton_all")
        self.radioButton_inc = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_inc.setChecked(True)
        self.radioButton_inc.setObjectName("radioButton_inc")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.lineEdit_date = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.gridLayout_3.addWidget(self.lineEdit_date, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.comboBox = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton.setMinimumSize(QtCore.QSize(131, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(131, 23))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.progressBar = QtWidgets.QProgressBar(self.splitter_3)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(131, 23))
        self.pushButton_2.setMaximumSize(QtCore.QSize(131, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.splitter_3, 1, 0, 1, 1)
        self.label_codename = QtWidgets.QLabel(self.groupBox)
        self.label_codename.setText("")
        self.label_codename.setObjectName("label_codename")
        self.gridLayout.addWidget(self.label_codename, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.pushButton.clicked.connect(Dialog.Backup_One) # type: ignore
        self.pushButton_2.clicked.connect(Dialog.Backup_All) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "종목별투자자정보 백업"))
        self.groupBox_3.setTitle(_translate("Dialog", "백업방법"))
        self.radioButton_all.setText(_translate("Dialog", "전체 백업"))
        self.radioButton_inc.setText(_translate("Dialog", "추가 백업"))
        self.label.setText(_translate("Dialog", "기준일자"))
        self.groupBox.setTitle(_translate("Dialog", "일봉"))
        self.pushButton.setText(_translate("Dialog", "한 종목 백업"))
        self.pushButton_2.setText(_translate("Dialog", "전 종목 백업"))
